name: Test Single Event GitHub Action

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "Hello from GitHub Actions!"

      - name: Display Date
        run: date

      - name: List Repository Files
        run: ls -lrt
