name: Test Cron GitHub Action
on :
  schedule:
    - cron: '35 21 * 7 5'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print Message
        run: echo "Workflow started manually."